# Database Configuration - SERVER DI PRODUZIONE (Cambia con i dati reali)
spring.datasource.url=jdbc:mysql://IP_DEL_SERVER_PROD:3306/vlfmskdb_prod?useSSL=true&serverTimezone=UTC
spring.datasource.username=vlfmskdb
spring.datasource.password=::csvPaid--..

# Code-first blindato per la Produzione (Controlla ma NON modifica il DB)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Sicurezza e JWT in Produzione 
app.jwt.secret=ItK6bW9vXzYq8N2pZ5mR4vW7xZ1aQ3bC5eF7gG9hI2jK4lM6nO8pQ0rS2tU4vW6xZ
logging.level.org.springframework.security=INFO

# reCAPTCHA
google.recaptcha.secret=6LdaQa0sAAAAAFZ3gmTAC1IVG5JN8aKdNTHOJGX5